pool:
  vmImage: 'win1803'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    choco install yarn --version 1.9.4
  displayName: 'install yarn'

- bash: |
    yarn install
  displayName: 'yarn install'

- bash: |
    yarn ci:test
  displayName: 'yarn ci:test'
