pool:
  vmImage: 'win1803'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    choco install yarn --version 1.9.4 -i -r
    echo "##vso[task.prependpath]C:\Program Files (x86)\Yarn\bin"
  displayName: 'install yarn'

- script: |
    yarn install
  displayName: 'yarn install'

- script: |
    yarn ci:test
  displayName: 'yarn ci:test'
